### ISSUE TITLE
Problem with Openpyxl

### ISSUE THREAD

**Issue by RsSchurl** [waldbaer/knx-ga-exporter#1]
I have an error Running the Project 
I Use a WSL Ubuntu ... All Files are in the Base Folder of the Project
Any Idea what could be the Problem ?

INFO:root:Loading XLSX input file 'KNX-planning-example.xlsx'
ERROR:root:Any error has occured! Traceback:
Traceback (most recent call last):
  File "/home/***/python/KnxExporter/knx-ga-exporter.py", line 246, in <module>
    main()
  File "/home/***/python/KnxExporter/knx-ga-exporter.py", line 32, in main
    wb = LoadWorkbook(args.input_file)
  File "/home/***/python/KnxExporter/knx-ga-exporter.py", line 122, in LoadWorkbook
    wb = load_workbook(filename=input_file, read_only=True, data_only=True)
  File "/home/***/python/KnxExporter/.venv/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
    reader.read()
  File "/home/***/python/KnxExporter/.venv/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 303, in read
    self.parser.assign_names()
  File "/home/***/python/KnxExporter/.venv/lib/python3.10/site-packages/openpyxl/reader/workbook.py", line 109, in assign_names
    sheet.defined_names[name] = defn
AttributeError: 'ReadOnlyWorksheet' object has no attribute 'defined_names'

**Comment by waldbaer** [comment]
@RsSchurl can you please tell me which version of openpyxl is actually installed in your venv?

Maybe I should change the requirements.txt to a concrete version.

**Comment by waldbaer** [comment]
Hello @RsSchurl the reported exception seems to be caused by a known openpyxl issue ([#1963](https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1963)).

As a workaround I forced the installation of the previous openpyxl version **3.1.0** instead of the latest 3.1.1.

Unfortunately I could not reproduce the issue on my local linux machine at all (even with a read-only Excel sheet).
Can you please try if the downgrade to openpyxl 3.1.0 fixes the issue for you?

Steps to downgrade:
- Pull the latest version of knx-ga-exporter.
- `setup-venv.sh`
- `pip install --force-reinstall -r requirements.txt`

or manually install the openpyxl version:
`pip install --force-reinstall openpyxl==3.1.0`

Would be nice if you give me some feedback of this fixes the issue for you. Thanks!
